### ISSUE TITLE
Is it possible to store the data into it.

### ISSUE THREAD

**Issue by Rajkumar181** [piersfinlayson/esp-sdk-samples#1]
I want to store the data into esp8266, like SSID and Password.

**Comment by piersfinlayson** [comment]
OK.  If you were using the [wifi_rssi](https://github.com/piersfinlayson/esp-sdk-samples/tree/master/wifi_rssi) sample then in [user_main.c](https://github.com/piersfinlayson/esp-sdk-samples/blob/master/wifi_rssi/user_main.c) you'd replace:

`    wifi_station_set_config_current(&wifi_conf);`

with:

`    wifi_station_set_config(&wifi_conf);`

That stores the SSID and password on the flash to use next time when connecting.

If you want to store other stuff on the esp8266's flash then you could take a look at the [eeprom](https://github.com/piersfinlayson/esp-sdk-samples/tree/master/eeprom) sample, but you'll probably find simpler ones elsewhere.

**Comment by Rajkumar181** [comment]
Thanks for your great reply
